cluster:
  name: "..."  # required, used as a prefix for all resources
  datacenter: "${c.datacenter}"  # required, will be the same for all nodes in the cluster
  ssh-key:  # required, fill in the private and public keys for the cluster, will be used for ssh access to all nodes
    private: |
      -----BEGIN OPENSSH PRIVATE KEY-----
      ...
      -----END OPENSSH PRIVATE KEY-----
    public: |
      ssh-...
  private-network:
    name: "lan-..."  # required, lan network name, must be created in advance with enough ips for all the nodes in the cluster
  default-node-config:  # default values for all nodes in the cluster
    # following values were filled in from the selected configurations
    cpu: "${c.cpuCores}${c.cpuType}"
    ram: "${c.ram}"
    disk: "${c.diskSizes.join(",")}"
    billingcycle: "${c.billing}"
    monthlypackage: "${c.billing === "monthly" ? c.netpack : ""}"
    # dailybackup: "yes"
    # managed: "yes"

  # server: "https://1.2.3.4:9345"  # optional, in case you want to use a specific server as the main cluster server
  # token: "..." # optional, to use as the cluster join token, if not provided will try to get it from controlplane-1 node
  # controlplane-server-name: ".."  # optional, if you want to specify the primary controlplane node name
  # allow-high-availability: true  # optional, if you want to enable high availability for the controlplane
  #                                # requires some work to setup, see https://docs.rke2.io/install/ha for details
  # default-rke2-server-config:  # optional, rke2 config which will be merged into the rke2 config for all server nodes (controlplane)
  #                              # see https://docs.rke2.io/reference/server_config for details
  # default-rke2-agent-config:  # optional, rke2 config which will be merged into the rke2 config for all nodes except the controlplane nodes
  #                             # see https://docs.rke2.io/reference/linux_agent_config for details


# modify the node pools as needed, following are some examples
node-pools:
  # controlplane:  # optional, the controlplane node pool is created anyway with 1 node
  #   nodes: 1  # only if allow-high-availability is true you can set to 3 / 5 / 7 for HA cluster
  #   node-config:  # optional, default values for all nodes in this pool
  #   rke2-config:  # optional, rke2 config which will be merged into the rke2 config for all nodes in this pool
  workers:
    nodes: 3
    node-config:  # optional, default values for all nodes in this pool override the cluster default-node-config
      cpu: 4B
      memory: 2048
    # rke2-config:  # optional, rke2 config which will be merged into the rke2 config for all nodes in this pool
  worker2:
    nodes: [5, 6]  # nodes can also be specified like this to keep specific node numbers
