name: CI
on:
  push:
jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - env:
        KAMATERA_API_CLIENT_ID: ${{ secrets.KAMATERA_API_CLIENT_ID }}
        KAMATERA_API_SECRET: ${{ secrets.KAMATERA_API_SECRET }}
        KAMATERA_API_SERVER: "https://cloudcli.cloudwm.com"
        DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
        DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
      run: |
        mkdir .cloudcli-server &&\
        wget https://github.com/cloudwm/cloudcli-server/archive/master.zip -O .cloudcli-server/cloudcli-server.zip &&\
        ( cd .cloudcli-server && unzip -q cloudcli-server.zip ) &&\
        rm .cloudcli-server/cloudcli-server.zip &&\
        echo "${DOCKER_HUB_PASSWORD}" | docker login -u "${DOCKER_HUB_USER}" --password-stdin &&\
        docker pull cloudwm/cloudcli-server &&\
        docker build -t cloudwm/cloudcli-server --cache-from cloudwm/cloudcli-server .cloudcli-server/cloudcli-server-master &&\
        docker push cloudwm/cloudcli-server &&\
        docker run -e CLOUDCLI_PROVIDER=proxy -e CLOUDCLI_API_SERVER=https://console.kamatera.com \
                   -e LOG_CHANNEL=errorlog -e APP_DEBUG=true \
                   --name cloudcli-server --rm -d -p 8000:80 cloudwm/cloudcli-server &&\
        export KAMATERA_API_SERVER=http://localhost:8000 &&\
        sudo apt-get install -y python3-venv &&\
        python3 -m venv venv &&\
        venv/bin/python3 -m pip install --upgrade pip &&\
        venv/bin/python3 -m pip install --upgrade setuptools wheel &&\
        venv/bin/python3 -m pip install -r requirements.txt &&\
        venv/bin/pytest -n 4
        PYTEST_EXITCODE=$?
        if [ "${PYTEST_EXITCODE}" != "0" ]; then
          docker logs cloudcli-server
        fi
        docker rm -f cloudcli-server
        exit $PYTEST_EXITCODE
