on:
  push:

jobs:
  buildpush:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          push: true
          file: Dockerfile.pages
          tags: ghcr.io/kamatera/kamateratoolbox:${{ github.sha }}
          cache-from: ghcr.io/kamatera/kamateratoolbox:latest
      - if: github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v6
        with:
          push: true
          file: Dockerfile.pages
          tags: ghcr.io/kamatera/kamateratoolbox:latest
          cache-from: ghcr.io/kamatera/kamateratoolbox:latest
