on:
  push:

jobs:
  buildpush:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          file: Dockerfile.pages
          push: true
          tags: |
            ghcr.io/kamatera/kamateratoolbox:${{ github.sha }}
            ${{ github.ref == 'refs/heads/master' && 'ghcr.io/kamatera/kamateratoolbox:latest' || '' }}
          cache-from: type=registry,ref=ghcr.io/kamatera/kamateratoolbox:latest
          cache-to: type=inline
